# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db3a2e4906fa104689904c16b9ee27b37a57cc25e1dd7e7571dab48227ba883cd57fa35d2cb016f78e2bdde02b278d8196fd0f87053333a12ca4c2678448c63

test:
  secret_key_base: a0b20e2c4ccbd52aac9eb6624c57188816d1f817cbc75b7a0be32b698b87272d55ec2293ed445f67b9ec1332e11b5afd50931f5745a95c91950df6b9d7dcffa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
